/**
 * LR parser generated by the Syntax tool.
 *
 * https://www.npmjs.com/package/syntax-cli
 *
 *   npm install -g syntax-cli
 *
 *   syntax-cli --help
 *
 * To regenerate run:
 *
 *   syntax-cli \
 *     --grammar ~/path-to-grammar-file \
 *     --mode <parsing-mode> \
 *     --output ~/path-to-output-parser-file.js
 */

'use strict';

interface TokenLocation {
  startOffset: number;
  endOffset: number;
  startLine: number;
  endLine: number;
  startColumn: number;
  endColumn: number;
}

interface Token extends Partial<TokenLocation> {
  type: string;
  value: string;
}

type ParseOptions = Record<string, unknown>;

interface YYContext {
  lexer: Tokenizer;
  tokenizer: Tokenizer;
  options: {
    captureLocations: boolean;
  } & ParseOptions;
}

type LexActionResult = string | string[] | void;
type LexRule = [RegExp, (this: Tokenizer) => LexActionResult];
type SemanticAction = (...args: unknown[]) => void;
type Production = [number, number, SemanticAction];
type TableEntry = string | number;

interface Tokenizer {
  _string: string;
  _cursor: number;
  _states: string[];
  _tokensQueue: string[];
  _currentLine: number;
  _currentColumn: number;
  _currentLineBeginOffset: number;
  _tokenStartOffset: number;
  _tokenEndOffset: number;
  _tokenStartLine: number;
  _tokenEndLine: number;
  _tokenStartColumn: number;
  _tokenEndColumn: number;
  initString(string: string): this;
  getStates(): string[];
  getCurrentState(): string;
  pushState(state: string): void;
  begin(state: string): void;
  popState(): string | undefined;
  getNextToken(): Token;
  throwUnexpectedToken(symbol: string, line: number, column: number): never;
  getCursor(): number;
  getCurrentLine(): number;
  getCurrentColumn(): number;
  _captureLocation(matched: string): void;
  _toToken(tokenType: string, yytext?: string): Token;
  isEOF(): boolean;
  hasMoreTokens(): boolean;
  _match(string: string, regexp: RegExp): string | null;
  onToken(token: Token): Token;
}

interface StackSymbolEntry {
  symbol: number | string;
  semanticValue?: unknown;
  loc?: TokenLocation | null;
}

interface YYParse {
  setOptions(options: YYContext['options']): YYParse;
  getOptions(): YYContext['options'];
  parse(string: string, parseOptions?: ParseOptions): unknown;
  setTokenizer(customTokenizer: Tokenizer): YYParse;
  getTokenizer(): Tokenizer;
  onParseBegin(string: string, tokenizer: Tokenizer, options: YYContext['options']): void;
  onParseEnd(parsed?: unknown): void;
  onShift(token: Token): Token;
}

/**
 * Matched token text.
 */
let yytext: string | null;

/**
 * Length of the matched token text.
 */
let yyleng: number | null;

/**
 * Storage object.
 */
const yy = {} as YYContext;

/**
 * Result of semantic action.
 */
let __: unknown;

/**
 * Result location object.
 */
const __loc: TokenLocation | null = null;

function yyloc(start: TokenLocation | null, end: TokenLocation | null): TokenLocation | null {
  if (!yy.options.captureLocations) {
    return null;
  }

  // Epsilon doesn't produce location.
  if (!start || !end) {
    return start || end;
  }

  return {
    startOffset: start.startOffset,
    endOffset: end.endOffset,
    startLine: start.startLine,
    endLine: end.endLine,
    startColumn: start.startColumn,
    endColumn: end.endColumn,
  };
}
void yyloc;

const EOF = '$';

/**
 * List of productions (generated by Syntax tool).
 */
const productions: Production[] = [[-1,1,(_1) => { __ = _1 }],
[0,1,(_1) => { __ = _1 }],
[0,1,(_1) => { __ = _1 }],
[1,1,(_1) => {  __ = Number(_1)  }],
[1,1,(_1) => { __ = _1 }],
[1,1,(_1) => { __ = _1 }],
[2,3,(_1,_2) => {  __ = _2  }],
[3,2,(_1,_2) => {  (_1 as unknown[]).push(_2); __ = _1  }],
[3,0,() => {  __ = []  }]];

/**
 * Encoded tokens map.
 */
const tokens: Record<string, string> = {"NUMBER":"4","STRING":"5","SYMBOL":"6","'('":"7","')'":"8","$":"9"};

/**
 * Parsing table (generated by Syntax tool).
 */
const table: Array<Record<string, TableEntry>> = [{"0":1,"1":2,"2":3,"4":"s4","5":"s5","6":"s6","7":"s7"},{"9":"acc"},{"4":"r1","5":"r1","6":"r1","7":"r1","8":"r1","9":"r1"},{"4":"r2","5":"r2","6":"r2","7":"r2","8":"r2","9":"r2"},{"4":"r3","5":"r3","6":"r3","7":"r3","8":"r3","9":"r3"},{"4":"r4","5":"r4","6":"r4","7":"r4","8":"r4","9":"r4"},{"4":"r5","5":"r5","6":"r5","7":"r5","8":"r5","9":"r5"},{"3":8,"4":"r8","5":"r8","6":"r8","7":"r8","8":"r8"},{"0":10,"1":2,"2":3,"4":"s4","5":"s5","6":"s6","7":"s7","8":"s9"},{"4":"r6","5":"r6","6":"r6","7":"r6","8":"r6","9":"r6"},{"4":"r7","5":"r7","6":"r7","7":"r7","8":"r7"}];

/**
 * Parsing stack.
 */
const stack: Array<number | StackSymbolEntry> = [];

/**
 * Tokenizer instance.
 */
let tokenizer: Tokenizer;
/**
 * Generic tokenizer used by the parser in the Syntax tool.
 *
 * https://www.npmjs.com/package/syntax-cli
 *
 * See `--custom-tokinzer` to skip this generation, and use a custom one.
 */

const lexRules: LexRule[] = [[/^\(/, function() { return "'('"; }],
[/^\)/, function() { return "')'"; }],
[/^\s+/, function() { /* skip whitespace */ }],
[/^"[^"]*"/, function() { return 'STRING' }],
[/^\d+/, function() { return 'NUMBER' }],
[/^[\w\-+*=<>/]+/, function() { return 'SYMBOL' }]];
const lexRulesByConditions: Record<string, number[]> = {"INITIAL":[0,1,2,3,4,5]};

const EOF_TOKEN = {
  type: EOF,
  value: '',
};

tokenizer = {
  initString(string: string) {
    this._string = string;
    this._cursor = 0;

    this._states = ['INITIAL'];
    this._tokensQueue = [];

    this._currentLine = 1;
    this._currentColumn = 0;
    this._currentLineBeginOffset = 0;

    /**
     * Matched token location data.
     */
    this._tokenStartOffset = 0;
    this._tokenEndOffset = 0;
    this._tokenStartLine = 1;
    this._tokenEndLine = 1;
    this._tokenStartColumn = 0;
    this._tokenEndColumn = 0;

    return this;
  },

  /**
   * Returns tokenizer states.
   */
  getStates() {
    return this._states;
  },

  getCurrentState() {
    return this._states[this._states.length - 1]!;
  },

  pushState(state: string) {
    this._states.push(state);
  },

  begin(state: string) {
    this.pushState(state);
  },

  popState() {
    if (this._states.length > 1) {
      return this._states.pop();
    }
    return this._states[0];
  },

  getNextToken() {
    // Something was queued, return it.
    if (this._tokensQueue.length > 0) {
      return this.onToken(this._toToken(this._tokensQueue.shift()!));
    }

    if (!this.hasMoreTokens()) {
      return this.onToken(EOF_TOKEN);
    }

    const string = this._string.slice(this._cursor);
    const lexRulesForState = lexRulesByConditions[this.getCurrentState()]!;

    for (let i = 0; i < lexRulesForState.length; i++) {
      const lexRuleIndex = lexRulesForState[i]!;
      const lexRule = lexRules[lexRuleIndex]!;

      const matched = this._match(string, lexRule[0]);

      // Manual handling of EOF token (the end of string). Return it
      // as `EOF` symbol.
      if (string === '' && matched === '') {
        this._cursor++;
      }

      if (matched !== null) {
        yytext = matched;
        yyleng = yytext.length;
        void yyleng;
        let token = lexRule[1].call(this);

        if (!token) {
          return this.getNextToken();
        }

        // If multiple tokens are returned, save them to return
        // on next `getNextToken` call.

        if (Array.isArray(token)) {
          const tokensToQueue = token.slice(1);
          token = token[0];
          if (tokensToQueue.length > 0) {
            this._tokensQueue.unshift(...tokensToQueue);
          }
        }

        return this.onToken(this._toToken(token as string, yytext));
      }
    }

    if (this.isEOF()) {
      this._cursor++;
      return EOF_TOKEN;
    }

    this.throwUnexpectedToken(
      string[0]!,
      this._currentLine,
      this._currentColumn
    );
  },

  /**
   * Throws default "Unexpected token" exception, showing the actual
   * line from the source, pointing with the ^ marker to the bad token.
   * In addition, shows `line:column` location.
   */
  throwUnexpectedToken(symbol: string, line: number, column: number): never {
    const lineSource = this._string.split('\n')[line - 1];
    let lineData = '';

    if (lineSource) {
      const pad = ' '.repeat(column);
      lineData = '\n\n' + lineSource + '\n' + pad + '^\n';
    }

    throw new SyntaxError(
      `${lineData}Unexpected token: "${symbol}" ` +
      `at ${line}:${column}.`
    );
  },

  getCursor() {
    return this._cursor;
  },

  getCurrentLine() {
    return this._currentLine;
  },

  getCurrentColumn() {
    return this._currentColumn;
  },

  _captureLocation(matched: string) {
    const nlRe = /\n/g;

    // Absolute offsets.
    this._tokenStartOffset = this._cursor;

    // Line-based locations, start.
    this._tokenStartLine = this._currentLine;
    this._tokenStartColumn =
      this._tokenStartOffset - this._currentLineBeginOffset;

    // Extract `\n` in the matched token.
    let nlMatch: RegExpExecArray | null;
    while ((nlMatch = nlRe.exec(matched)) !== null) {
      this._currentLine++;
      this._currentLineBeginOffset = this._tokenStartOffset + nlMatch.index + 1;
    }

    this._tokenEndOffset = this._cursor + matched.length;

    // Line-based locations, end.
    this._tokenEndLine = this._currentLine;
    this._tokenEndColumn = this._currentColumn =
      (this._tokenEndOffset - this._currentLineBeginOffset);
  },

  _toToken(tokenType: string, yytext = ''): Token {
    return {
      // Basic data.
      type: tokenType,
      value: yytext,

      // Location data.
      startOffset: this._tokenStartOffset,
      endOffset: this._tokenEndOffset,
      startLine: this._tokenStartLine,
      endLine: this._tokenEndLine,
      startColumn: this._tokenStartColumn,
      endColumn: this._tokenEndColumn,
    };
  },

  isEOF() {
    return this._cursor === this._string.length;
  },

  hasMoreTokens() {
    return this._cursor <= this._string.length;
  },

  _match(string: string, regexp: RegExp): string | null {
    const matched = string.match(regexp);
    if (matched) {
      // Handle `\n` in the matched token to track line numbers.
      this._captureLocation(matched[0]);
      this._cursor += matched[0].length;
      return matched[0];
    }
    return null;
  },

  /**
   * Allows analyzing, and transforming token. Default implementation
   * just passes the token through.
   */
  onToken(token: Token): Token {
    return token;
  },
} as Tokenizer;

/**
 * Expose tokenizer so it can be accessed in semantic actions.
 */
yy.lexer = tokenizer;
yy.tokenizer = tokenizer;

/**
 * Global parsing options. Some options can be shadowed per
 * each `parse` call, if the optations are passed.
 *
 * Initalized to the `captureLocations` which is passed
 * from the generator. Other options can be added at runtime.
 */
yy.options = {
  captureLocations: false,
};

/**
 * Parsing module.
 */
const yyparse: YYParse = {
  /**
   * Sets global parsing options.
   */
  setOptions(options: YYContext['options']) {
    yy.options = options;
    return this;
  },

  /**
   * Returns parsing options.
   */
  getOptions() {
    return yy.options;
  },

  /**
   * Parses a string.
   */
  parse(string: string, parseOptions?: ParseOptions) {
    if (!tokenizer) {
      throw new Error(`Tokenizer instance wasn't specified.`);
    }

    tokenizer.initString(string);

    /**
     * If parse options are passed, override global parse options for
     * this call, and later restore global options.
     */
    const globalOptions = yy.options;
    if (parseOptions) {
      yy.options = Object.assign({}, yy.options, parseOptions);
    }

    /**
     * Allow callers to do setup work based on the
     * parsing string, and passed options.
     */
    yyparse.onParseBegin(string, tokenizer, yy.options);

    stack.length = 0;
    stack.push(0);

    let token = tokenizer.getNextToken();
    let shiftedToken: Token | null = null;

    do {
      if (!token) {
        // Restore options.
        yy.options = globalOptions;
        unexpectedEndOfInput();
      }

      const state = stack[stack.length - 1] as number;
      const column = tokens[token.type]!;

      if (!Object.prototype.hasOwnProperty.call(table[state]!, column)) {
        yy.options = globalOptions;
        unexpectedToken(token);
      }

      const entry = table[state]![column]! as string;

      // Shift action.
      if (entry[0] === 's') {
        let loc = null;

        if (yy.options.captureLocations) {
          loc = {
            startOffset: token.startOffset!,
            endOffset: token.endOffset!,
            startLine: token.startLine!,
            endLine: token.endLine!,
            startColumn: token.startColumn!,
            endColumn: token.endColumn!,
          };
        }

        shiftedToken = this.onShift(token);

        stack.push(
          {symbol: tokens[shiftedToken.type]!, semanticValue: shiftedToken.value, loc},
          Number(entry.slice(1))
        );

        token = tokenizer.getNextToken();
      }

      // Reduce action.
      else if (entry[0] === 'r') {
        const productionNumber = Number(entry.slice(1));
        const production = productions[productionNumber]!;
        const hasSemanticAction = typeof production[2] === 'function';
        const semanticValueArgs: unknown[] = [];

        const locationArgs: Array<TokenLocation | null | undefined> | null = (
          hasSemanticAction && yy.options.captureLocations
            ? []
            : null
        );

        if (production[1] !== 0) {
          let rhsLength = production[1];
          while (rhsLength-- > 0) {
            stack.pop();
            const stackEntry = stack.pop() as StackSymbolEntry;

            if (hasSemanticAction) {
              semanticValueArgs.unshift(stackEntry.semanticValue);

              if (locationArgs) {
                locationArgs.unshift(stackEntry.loc);
              }
            }
          }
        }

        const reduceStackEntry: StackSymbolEntry = {symbol: production[0]};

        if (hasSemanticAction) {
          yytext = shiftedToken ? shiftedToken.value : null;
          yyleng = shiftedToken ? shiftedToken.value.length : null;

          const semanticActionArgs = (
            locationArgs !== null
              ? semanticValueArgs.concat(locationArgs)
              : semanticValueArgs
          );

          production[2](...semanticActionArgs);

          reduceStackEntry.semanticValue = __;

          if (locationArgs) {
            reduceStackEntry.loc = __loc;
          }
        }

        const nextState = stack[stack.length - 1];
        const symbolToReduceWith = production[0];

        stack.push(
          reduceStackEntry,
          table[nextState as number]![String(symbolToReduceWith)] as number
        );
      }

      // Accept.
      else if (entry === 'acc') {
        stack.pop();
        const parsed = stack.pop() as StackSymbolEntry;

        if (stack.length !== 1 ||
            stack[0] !== 0 ||
            tokenizer.hasMoreTokens()) {
          // Restore options.
          yy.options = globalOptions;
          unexpectedToken(token);
        }

        if (Object.prototype.hasOwnProperty.call(parsed, 'semanticValue')) {
          yy.options = globalOptions;
          yyparse.onParseEnd(parsed.semanticValue);
          return parsed.semanticValue;
        }

        yyparse.onParseEnd();

        // Restore options.
        yy.options = globalOptions;
        return true;
      }

    } while (tokenizer.hasMoreTokens() || stack.length > 1);
  },

  setTokenizer(customTokenizer: Tokenizer) {
    tokenizer = customTokenizer;
    return yyparse;
  },

  getTokenizer() {
    return tokenizer;
  },

  onParseBegin(string: string, tokenizer: Tokenizer, options: YYContext['options']) {
    void string;
    void tokenizer;
    void options;
  },
  onParseEnd(parsed?: unknown) {
    void parsed;
  },

  /**
   * Allows analyzing, and transforming shifted token. Default implementation
   * just passes the token through.
   */
  onShift(token: Token) {
    return token;
  },
};



function unexpectedToken(token: Token) {
  if (token.type === EOF) {
    unexpectedEndOfInput();
  }

  tokenizer.throwUnexpectedToken(
    token.value,
    token.startLine!,
    token.startColumn!
  );
}

function unexpectedEndOfInput() {
  parseError(`Unexpected end of input.`);
}

function parseError(message: string) {
  throw new SyntaxError(message);
}

export default yyparse;
